# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Faber' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Faber
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'FirebaseUI/Firestore', '~> 8.0'
  pod 'FirebaseUI/Email', '~> 8.0'
  pod 'FirebaseUI/Google', '~> 8.0'
  pod 'Firebase/Functions'
  pod 'SDWebImage', '~> 5.0'
  pod 'Shuffle-iOS'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'TensorFlowLiteSwift'
  pod 'TestFairy'
  
  target 'FaberTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
